---
- name: "Instalando Servidor LAMP"
  hosts: test-host
  remote_user: terra
  become: true
  vars_files:
    - vars/default.yml
  tasks:
    - name: Installando los upgrades del chubuntu
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

  #Apache Configuration
    - name: Installando las paquterias para la LAMPara 
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]

    - name: Creanding el dochumento para el folder root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Configurando el Mapache como virtualhost
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache

    - name: Habilitandole una nueva cria (sitio nuevo)
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache

    - name: Removiendo el sitio chafa que trae por default
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

  # Configurando el puerto de escucha en el firewall UFW
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

  # Clavandole la config del PHP Informaichon
    - name: Configurando el PHP Info
      template:
        src: "files/info.php.j2"
        dest: "/var/www/{{ http_host }}/info.php"

  handlers:
    - name: Recargando el Mapache
      service:
        name: apache2
        state: reloaded

    - name: Receteando el Mapache
      service:
        name: apache2
        state: restarted